--51. List the emps who joined before 1985 and salary is more than 3000.
SELECT E.*, TO_CHAR(HIREDATE, 'YYYY') HIREYEAR FROM EMP E WHERE TO_CHAR(HIREDATE, 'YYYY')< 1985 AND SAL > 3000;


--52. List the Exp of Grade 3 emps.
SELECT EMPNO, ENAME, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12)||' YEARS' AS EXPERIENCE 
FROM EMP 
    WHERE SAL > (SELECT LOSAL FROM SALGRADE WHERE GRADE = 3) 
    AND SAL < (SELECT HISAL FROM SALGRADE WHERE GRADE = 3);
 

--53. List the details of the emps whose salaries more than the employee BLAKE
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE')